#!/bin/env bash
# --- By Kiriyama and Clawbhaiya ---

whenrec=$(date +"%d-%m-%y_%H-%M_")

mode="alsa"

OUTPUT=~/Videos/Screenrecord/"${whenrec}.mp4"

FR=30 

deviceid=43

resolution=1366x768

TEMPDIR=~/.cache/recscreen

record_alsa () {
	ffmpeg \
		-use_wallclock_as_timestamps 1 \
		-f pulse -ac 2 -ar 44100 -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor \
		-f x11grab -r $FR -s 1366x768 -i :0.0 \
		-vf scale=$resolution:flags=lanczos \
		-vcodec libx264 -preset veryfast \
		-acodec libmp3lame -ar 44100 -q:a 1 \
		-pix_fmt yuv420p \
		$TEMPDIR/temp.mp4
	
	ffmpeg \
    	-i $TEMPDIR/temp.mp4 \
    	-itsoffset $DEOFFSET \
    	-i $TEMPDIR/temp.mp4 \
    	-vcodec copy -acodec copy \
    	-map 0:0 -map 1:1 \
    	$OUTPUT
		
	rm -rf $TEMPDIR
}

record_pipewire () {
	pw-record --target $deviceid $TEMPDIR/audio.wav & \
	ffmpeg \
    	-f x11grab -framerate $FR -i :0.0 \
    	-vcodec libx264 -crf 7 \
    	-vf scale=$resolution\
    	-preset superfast \
    	$TEMPDIR/video.mkv 

	ffmpeg \
    	-i $TEMPDIR/video.mkv -i $TEMPDIR/audio.wav \
    	-c:v copy -map 0:v:0 -map 1:a:0 -c:a aac -b:a 300k \
    	$OUTPUT

	rm -rf $TEMPDIR
}

help () {
	echo "Recscreen by Kiriyama"
	echo
	echo "[-h] show help menu"
	echo "[-o OUTPUT ] specify output video name"
	echo "[-f FPS ] specify the number of Frames per Second"
	echo "[-r RESOLUTION ] specify the resolution in pixels in WIDTHxHEIGHT format"
	echo "[-p] use pipewire instead of alsa"
	echo
}

main () {

	if [ ! -d $TEMPDIR ] ; then
		mkdir -p ~/.cache/recscreen
	fi
	
	if [ ! -d ~/Videos/Screenrecord ] ; then
		mkdir -p ~/Videos/Screenrecord
	fi

	while getopts ":hpf:o:r:" options; do
		case "${options}" in
		h)
			help
			exit 0
			;;
		o)
			OUTPUT="${OPTARG}"
			;;
		f)
			FR="${OPTARG}"
			;;
		p)
			mode="pipewire"
			;;
		r)
			resolution="${OPTARG}"
			;;
		:)
			echo "Error: -${OPTARG} requires an argument."
			exit 1
			;;
		*)
			echo "Error: Unknown option -${OPTARG}."
			exit 1
			;;
		esac
	done

	if [ "$mode" = "pipewire" ] ; then
		record_pipewire
	elif [ "$mode" = "alsa" ] ; then
		record_alsa
	fi
}

main $@
